[build-system]
requires = ["hatchling>=1.27.0", "packaging>=24.2"]
build-backend = "hatchling.build"

[project]
name = "xtce2py"
version = "0.1.0a1"
description = "A generator for creating a Python package toolkit from an XTCE file."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.11"
authors = [{ name = "Nathan Miersen", email = "nrmiersen@gmail.com" }]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "pydantic>=2.11.7",
    "xsdata>=25.7",
    "jinja2>=3.1.6",
    "typer>=0.16.0",
    "ruff>=0.12.4",
    "rich>=10.0.0",
    "lxml>=6.0.0",
    "lxml-stubs>=0.5.1",
    "pydantic-settings>=2.11.0",
]

[project.scripts]
xtce2py = "xtce2py.__main__:main"

[project.urls]
Homepage = "https://github.com/nrmiersen/xtce2py"
Repository = "https://github.com/nrmiersen/xtce2py"

[dependency-groups]
dev = ["xsdata[cli]>=25.7", "xtce-codec==0.1.0a5", "build>=1.4.0"]

[tool.pdm]
distribution = true

[tool.pdm.scripts]
xtce2py = "python -m xtce2py.main"

[tool.hatch.build.targets.wheel]
packages = ["src/xtce2py"]

[tool.hatch.build.targets.sdist]
include = ["src/xtce2py", "README.md", "LICENSE", "pyproject.toml"]

[tool.ruff]
line-length = 88
exclude = [
    "src/xtce2py/xtce_1_1/bindings/models.py",
    "src/xtce2py/xtce_1_2/bindings/models.py",
    "src/xtce2py/xtce_1_3/bindings/models.py",
]
[tool.ruff.lint]
select = [
    "D", # pydocstyle
    "I", # isort
    "F", # pyflakes
]
ignore = [
    "D203", # Conflicts with D211
    "D213", # Conflicts with D212
]
[tool.ruff.lint.isort]
known-first-party = ["xtce2py"]
