[author]
name = "Nathan Miersen"
email = "nrmiersen@gmail.com"

[package_defaults]
license = "MIT"

[naming_convention]
style = "keep"
acronyms = ["CCSDS", "EPS"]

[logging]
level = "INFO"
file = "xtce2py.log"
