[author]
name = "Nathan Miersen"
email = "nrmiersen@gmail.com"

[package_defaults]
suffix = "toolkit"
license = "MIT"

[naming_convention]
use_existing_names = true
acronyms = ["CCSDS", "EPS"]

[logging]
# level = "DEBUG"
# file = "~/xtce2py_output/xtce2py.log"
